apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
